adds ronin testnet
smartcontractkit/chain-selectors pull request #55
Opened 2024-09-16 15:44 UTC by amaechiokolobi

2024-09-16 20:50 UTC, andrevmatos requested changes

2024-09-16 20:50 UTC, andrevmatos commented on selector_families.yml
> +    name: ethereum-testnet-seigon-ronin-1
Please, update here accordingly

2024-09-17 08:28 UTC, amaechiokolobi commented on selector_families.yml
> +    name: ethereum-testnet-seigon-ronin-1
fixed

2024-09-17 17:44 UTC, andrevmatos approved these changes

2024-09-17 18:49 UTC, merged